### ISSUE TITLE
Regarding to Milestone3

### ISSUE THREAD

**Issue by xiaoweideng** [UBC-MDS/DSCI_532_Suicide_Statistics#12]
Hey Rayce,
I have just done the 4 world plots for the world tab. They are all functioning now and interactive with the year slider. I also changed the y-axis to suicide rate for the plot 1,4 and forced the y-axis to start at 0 for plot 2,3.

Here are something left for you.
1. While I were wrangling for the plot7, there are missing population values during 2013 and 2014 therefore the line chart is not continuous. However, this is not due to the missing data because there actually are population value after I group by year and sex. Hope you can solve this problem.
2. Let sex input interact with plot1,3,4,7,8.
3. Add "All" sex option to the legend titles.
4. Make plots prettier.

**Comment by RayceRossum** [comment]
Hey Wilson, I've added this to the latest PR. Please check it out and close this issue when you can.
